# Generated by Django 4.2.7 on 2024-01-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRCodeApp', '0002_login_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Full_Name',
            new_name='Name',
        ),
    ]
