# Generated by Django 4.2.7 on 2024-01-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCodeApp', '0003_delete_login_rename_full_name_register_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
