# Generated by Django 4.2.7 on 2024-01-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCodeApp', '0005_remove_userdata_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qr_codes/')),
            ],
        ),
    ]
