# Generated by Django 4.2.7 on 2024-01-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCodeApp', '0006_qrimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRImage',
        ),
        migrations.AddField(
            model_name='userdata',
            name='QRCodeImage',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
