# Generated by Django 4.2.7 on 2024-01-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRCodeApp', '0007_delete_qrimage_userdata_qrcodeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Input',
            new_name='input_data',
        ),
    ]
