# Generated by Django 4.2.7 on 2024-01-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRCodeApp', '0008_rename_input_userdata_input_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='input_data',
            new_name='Input',
        ),
    ]
